### ISSUE TITLE
Broken Links in README

### ISSUE THREAD

**Issue by elmarti** [DVELP/cookbook#133]
Hi DVELP, I'm just having a look through your cookbook and thought i'd list a few issues: 

The following anchor tags don't link to anything

- Big, Hairy, Audacious Goal - https://github.com/DVELP/cookbook#big-hairy-audacious-goal
- The Constitution - https://github.com/DVELP/cookbook#the-constitution

And the following links

- The DVELP Process - https://github.com/DVELP/cookbook/blob/master/guides/project-process/dvelp-process.md
- Softphone - https://github.com/DVELP/cookbook/blob/master/guides/tools/soft-phone.md

**Comment by alvaro-chalar** [comment]
Thanks for reporting it @elmarti !
